from app.models.models import (  # noqa: F401
    Appointment,
    Clinic,
    Doctor,
    DoctorSlot,
    DiseaseCase,
    EnvironmentalObservation,
    Notification,
    OutbreakAlert,
    Patient,
    Prediction,
    SymptomSubmission,
    HealthConversation,
    HealthIntake,
    UserSession,
    User,
)
